TimeStamped Data
indygreg/cryptography-rs pull request #7
Opened 2023-03-04 10:18 UTC by enri1196

Thanks to your work i was able to serialize documents with time stamps as defined by rfc5544, hopefully you'll find this PR useful. The last missing piece would be verification, which i'm not too familiar with.

2023-03-19 20:35 UTC, indygreg commented
Thanks for the contribution! I'm going to look at this now.

I'll likely split this up into different commits to make it easier for me to review. e.g. committing the new ASN.1 types first then look at the code that uses them. I'll preserve your authorship on the commits to reflect your contribution.

2023-03-19 21:05 UTC, indygreg requested changes
Thanks for coding this!

I'm going to commit changes to the `x509-certificate` crate since they look OK.

But the CMS crate changes need a bit of work.

Also, I'm not familiar with the new RFCs. Do you have examples of software producing messages using these new types? If possible, I'd like to commit files so we can validate parsing.

2023-03-19 21:05 UTC, indygreg commented on cryptographic-message-syntax/src/asn1/rfc4998.rs
> +    pub version: CmsVersion,
Since only `v1(1)` is a valid value, we should have a dedicated enum for this field. That is a bit wasteful having an enum with a single variant. But it is semantically called for.

But if you want to save some work, I'll let you elide the enum and just store a `u8`. Just as long as we validate it is an integer of value 1 during parsing.

2023-03-19 21:05 UTC, indygreg commented on cryptographic-message-syntax/src/asn1/rfc4998.rs
> +    pub digest_algorithms: AlgorithmIdentifier,
The RFC says this is a `SEQUENCE OF AlgorithmIdentifier`. So this should be a `Vec<AlgorithmIdentifier>`.

2023-03-19 21:05 UTC, indygreg commented on cryptographic-message-syntax/src/asn1/rfc4998.rs
> +    }
I think this method can safely be deleted.

2023-03-19 21:05 UTC, indygreg commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +    pub version: CmsVersion,
Same comment as above regarding not reusing `CmsVersion`.

2023-03-19 21:05 UTC, indygreg commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +    }
I'll need to read the RFC on BER/DER handling. Any time you see this special handling for BER mode it is annoying. There have been multiple bugs in the CMS create due to it. Not helping is that not all implementations always use BER mode.

2023-03-19 21:05 UTC, indygreg commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +    }
I _think_ this is attempting to decode a `ContentInfo` type? Seems weird to have this method on `TimeStampedData`. Could you please create a `ContentInfo` struct and move this logic to it? Also, I think `decode_ber()` goes in `ContentInfo` as well, right?

2023-03-19 21:05 UTC, indygreg commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +        })?;
I think this can be `cons.take_bool()`.

2023-03-19 21:05 UTC, indygreg commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +        println!("HASHPROT: {hash_protected:?}");
Forgot to delete a debugging statement.

2023-03-19 21:05 UTC, indygreg commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +        })
Forgot to decode the remaining fields. Either implement this, raise an error, or delete the fields since they are never populated.

2023-03-19 21:05 UTC, indygreg commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +            Ok(Self::OtherEvidence(other_evidence))
Since these fields are not optional, this should use `cons.take_constructed_if`.

2023-03-27 17:46 UTC, enri1196 commented
> Thanks for coding this!
> 
> I'm going to commit changes to the `x509-certificate` crate since they look OK.
> 
> But the CMS crate changes need a bit of work.
> 
> Also, I'm not familiar with the new RFCs. Do you have examples of software producing messages using these new types? If possible, I'd like to commit files so we can validate parsing.

First of all thanks for taking a look at my MR, once I've some more time from work I'll try to implement all the suggestions above.

I'll see what I can do to get a file example, because I was trying to verify some files that I cannot freely upload and I wanted to implement that verification in Rust. Softwares that can verify these files should be Aruba Sign or Dike GoSign.

2023-04-12 09:02 UTC, enri1196 commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +            Ok(Self::OtherEvidence(other_evidence))
Since it could be any of these three types, i use this pattern to match against the first valid type or an error is returned

2023-04-12 09:03 UTC, enri1196 commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +        })
should be ok now

2023-04-12 09:04 UTC, enri1196 commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +        println!("HASHPROT: {hash_protected:?}");
deleted

2023-04-12 09:04 UTC, enri1196 commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +        })?;
yeah, fixed

2023-04-12 09:05 UTC, enri1196 commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +    }
i've actually took "inspiration" form other parts of the code, if a user tries to parse a file which is not timestamped data type it should raise an error

2023-04-12 09:07 UTC, enri1196 commented on cryptographic-message-syntax/src/asn1/rfc5544.rs
> +    pub version: CmsVersion,
since it's an extension of the CMS specification i thought it was the correct thing to do

2023-05-06 16:56 UTC, closed without merging